GoltAd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView
    
)
from GoltUser.views import LandingPage,indexView,RefSignupView
from allauth.account.views import LoginView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', indexView.as_view(), name='landing-page'),
    path('accounts/', include('allauth.urls')),
    path('accounts/<str:ref_code>/', RefSignupView.as_view(),name='ref-signup'),
    path('index/', indexView.as_view(),name='index'),
    
    # path('login/', LoginView.as_view(), name='login'),
    path('goldburry/', include('GoltUser.urls',namespace='golt')),
    path('mgt/', include('UserMgt.urls',namespace='mgt'))
    
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

GoltUser/urls.py
from django.urls import path,include
from .views import AdTypeView,selectCategory,UnSelectCategory, AdDetailView, ADcheck,CreateCompanyView,AdCreateView,ProfileUpdateView,CompanyUpdateView,CreateProfileView,UserProfileView,profile_delete,CompanyView

app_name = 'golt'

urlpatterns = [
    path('categories/', AdTypeView.as_view(), name='categories'),
    path('create-company/', CreateCompanyView.as_view(), name='create-company'),
    path('select_category/<int:pk>', selectCategory.as_view(), name='cat-select'),
    path('unselect_category/<int:pk>', UnSelectCategory.as_view(), name='cat-unselect'),
    path('profile/<int:pk>', ProfileUpdateView.as_view(), name='update-profile'),
    path('profile-delete/<int:pk>',profile_delete,name='profile-delete'),
    path('update-company/<int:pk>', CompanyUpdateView.as_view(), name='update-company'),
    path('<int:pk>/detail/', AdDetailView.as_view(), name='ad-detail'),
    path('<int:pk>/<int:ad_pk>/detail/', ADcheck.as_view(), name='adcheck'),
    path('create-ad/', AdCreateView.as_view(), name='create-ad'),
    path('profile/', CreateProfileView.as_view(), name='create-profile'),
    path('company/', CreateCompanyView.as_view(), name='create-company'),
    path('user-profile/<int:pk>', UserProfileView.as_view(), name='profile'),
    path('company/<int:pk>', CompanyView.as_view(), name='company'),
    
    
    
    
    
    
    
    ]

UserMgt/urls.py
from .views import InitiatePayment,VerifyPayment,VerifyAccount
from django.urls import path
app_name = 'mgt'

urlpatterns = [
    path('',InitiatePayment.as_view(), name="initiate-payment"),
    path('<str:ref>/', VerifyPayment.as_view(), name="verify-payment"),
    path('<int:pk>/verify_account/', VerifyAccount.as_view(), name="verify-account"),
    
    
]

templates/ad-details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container ">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="{% url 'index' %}"><i class="fa fa-home"></i> Home</a>
                        <a href="{% url 'golt:categories' %}">{{ad.ad_type}}</a>
                        <span>{{ad.company.company_name}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Anime Section Begin -->
    <section class="anime-details spad">
        <div class="container">
            <div class="anime__details__content">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="anime__details__pic set-bg" data-setbg={{ad.photo.url}}  >
                            <div class="comment"><i class="fa fa-comments"></i> 11</div>
                            <div class="view"><i class="fa fa-eye"></i> {{ad.get_ad_count}}</div>
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <div class="anime__details__text">
                            <div class="anime__details__title">
                                <h3>{{ad.company.company_name}}</h3>
                                <span>{{ad.name}}</span>
                            </div>
                            <p>{{ad.ad_description}}</p>
                            <div class="anime__details__widget">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6">
                                        <ul>
                                            <li><span>Category:</span>{{ad.ad_type}}</li>
                                            <li><span>Date added:</span> date</li>
                                            <li><span>Expires:</span> Oct 02, 2019 to ?</li>
                                            <!-- <li><span>Status:</span>onboard</li> -->
                                            <li><span>Audience</span>Kids, Adult</li>
                                        </ul>
                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <ul>
                                            <li><span>Positivity:</span>1354 </li>
                                            <li><span>Negativity:</span> 1562</li>
                                            <li><span>Rating:</span>18+</li>
                                            <li><span>Views:</span>{{ad.get_ad_count}} Users</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="anime__details__btn">
                                
                                {% if request.user.userprofile == ad.company.userprofile %}
                                <a href="{% url 'golt:adcheck' user.pk ad.pk %}" target="_blank" class="watch-btn"><span>Check Total Connection</span> <i
                                    class="fa fa-angle-right"></i></a>
                                
                                    {% elif request.user.userprofile in ad.users.all %}
                                    <a href="" class="follow-btn"><i class="fa fa-share"></i> share</a>
                                    <a target="_blank" class="watch-btn"><span>Visited</span> <i
                                        class="fa fa-angle-right"></i></a>
                                    {% else %}
                                <a href="" class="follow-btn"><i class="fa fa-share"></i> share</a>
                                <a href="{% url 'golt:adcheck' user.pk ad.pk %}"class="watch-btn" id="ad-btn"><span>Visit</span> <i
                                    class="fa fa-angle-right"></i></a></a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-8 col-md-8">
                        <div class="anime__details__review">
                            <div class="section-title">
                                <h5>Reviews</h5>
                            </div>
                            <div class="anime__review__item">
                                <div class="anime__review__item__pic">
                                    <img src={%  static "img/anime/review-1.jpg" %} alt="">
                                </div>
                                <div class="anime__review__item__text">
                                    <h6>Chris Curry - <span>1 Hour ago</span></h6>
                                    <p>whachikan Just noticed that someone categorized this as belonging to the genre
                                    "demons" LOL</p>
                                </div>
                            </div>
                          
                        </div>
                        <div class="anime__details__form">
                            <div class="section-title">
                                <h5>Your Comment</h5>
                            </div>
                            <form action="#">
                                <textarea placeholder="Your Comment"></textarea>
                                <button type="submit"><i class="fa fa-location-arrow"></i> Review</button>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="anime__details__sidebar">
                            <div class="section-title">
                                <h5>Ads from this business</h5>
                            </div>
                            <div class="product__sidebar__view__item set-bg" data-setbg={%  static "img/site-img/img44.jpg" %}>
                                <div class="ep">18 / </div>
                                <div class="view"><i class="fa fa-eye"></i> 9141</div>
                                <h5><a href="#">Great things comes uneasy</a></h5>
                            </div>
                          
                            
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Anime Section End -->
{% endblock content %}

templates/cat_choice.html
{% extends "base.html" %}
{% block content %}
{% load static %}
  <section class="mt-5 ms-5 container mb-5">
 
      <div class="container-flyuid">
        <div class="row">
            <div class="col-lg-12">
                <div class="trending__product">
                    <div class="row">
                        <div class="col-lg-8 col-md-8 col-sm-8 mt-5">
                            <div class="section-title">
                                <h4>Choose Ads you would love to see</h4>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <div class="btn__all">
                                <a href="#" class="primary-btn">View All <span class="arrow_right"></span></a>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                      {% for cats in adtype %}
                      <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <div class="card">
                          <div class="card-statistic-4">
                            <div class="align-items-center justify-content-between">
                              <div class="row ">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 pr-0 pt-3">
                                  <div class="card-content">
                                    <h5 class="font-15">{{cats.name}}</h5>
                                    <h2 class="mb-3 font-18">{{cats.get_count}}</h2>
                                    {% if request.user.userprofile in cats.user.all %}
                                          <a href="{% url 'golt:cat-unselect' cats.pk %}" class="ms-5 ps-5"> <span class="text-danger mx-2" style="font-size: 0.8rem; text-decoration:underline;">unselect</span></a>
                                          {% else %}
                                          <a href="{% url 'golt:cat-select' cats.pk %}" class="ms-5 ps-5"> <span class="text-info mx-2" style="font-size: 0.8rem; text-decoration:underline;">select</span></a>
                                        {% endif %}
                                  </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 pl-0">
                                  <div class="banner-img">
                                    <img src= {% static "assets/img/banner/4.png" %} alt="">
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      {% endfor %}
                         
                       
                      
                        
                    </div>
                </div>
            </div>
        </div>
      </div>
  </section>
{% endblock content %}

templates/create-company.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="main-content">
    <section class="section">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2">
            <div class="card card-warning">
              <div class="card-header">
                <h4>Add Business Profile</h4>
              </div>
              <div class="card-body">
                {% if request.user.profile.has_company %}
                <form action="{% url 'golt:update-company' company.pk %}" method="post" enctype="multipart/form-data">
                  {% else %}
                <form action="{% url 'golt:create-company' %}" method="post" enctype="multipart/form-data">
                  {% endif %}
                  {% csrf_token %}
                  <div class="row">
                    <div class="form-group col-6">
                      <label for="company_name">Business Name</label>
                      <input id="company_name" type="text" class="form-control" name="company_name" autofocus>
                    </div>
                  <div class="form-group col-6">
                    <label for="company_address">Business Address</label>
                    <input id="company_address" type="text" class="form-control" name="company_address">
                    <div class="invalid-feedback">
                    </div>
                  </div>
                </div>
                  <div class="row">
                    <div class="form-group col-6">
                      <label for="email" class="d-block">Email</label>
                      <input id="email" type="email" class="form-control pwstrength" data-indicator="pwindicator"
                        name="email">
                        <div class="invalid-feedback">
                        </div>
                    </div>
                    <div class="form-group col-6">
                      <label for="company_url" class="d-block">Web Address (www.youraddress.com)</label>
                      <input id="company_url" type="text" class="form-control" name="company_url">
                    </div>
                     <div class="invalid-feedback">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="custom-switch">
                      <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input" id="hide_btn">
                      <span class="custom-switch-indicator"></span>
                      <span class="custom-switch-description">use the same details in your profile for country,state,zip and contact</span>
                    </label>
                  </div>
                  <div id="disp">
                    <div class="row">
                      <div class="form-group col-6">
                        <label for="country" class="d-block">Country</label>
                        <input id="country" type="text" class="form-control pwstrength" data-indicator="pwindicator"
                          name="country">
                          <div class="invalid-feedback">
                          </div>
                      </div>
                      <div class="form-group col-6">
                        <label for="phone" class="d-block">Phone</label>
                        <input id="phone" type="name" class="form-control" name="phone">
                      </div>
                        <div class="invalid-feedback">
                      </div>
                    </div>
                    <div class="row">
                      <div class="form-group col-6">
                        <label for="state" class="d-block">State</label>
                        <input id="state" type="name" class="form-control pwstrength" data-indicator="pwindicator"
                          name="state">
                          <div class="invalid-feedback">
                          </div>
                      </div>
                      <div class="form-group col-6">
                        <label for="zip" class="d-block">zip</label>
                        <input id="zip" type="name" class="form-control" name="zip">
                      </div>
                        <div class="invalid-feedback">
                      </div>
                    </div>
                  </div>
                  <div class="form-group row mb-4 pl-3 pl-md-5">
                    <label class="col-form-label text-center col-10">Profile Photo</label>
                    <div class="col-sm-12 col-md-7 ml-2 ml-md-5 pl-md-5">
                      <div id="image-preview" class="image-preview ">
                        <label for="image-upload" id="image-label">Choose File</label>
                        <input type="file" name="photo" id="image-upload" />
                      </div>
                    </div>
                  </div>
                 
                  <div class="form-group">
                    {% if request.user.profile.has_company %}
                    <button type="submit" class="btn btn-warning btn-lg btn-block">
                      Update Company
                    </button>
                    {% else %}
                    <button type="submit" class="btn btn-warning btn-lg btn-block">
                      Create Company
                    </button>
                    {% endif %}

                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  {% endblock content %}
  
{% block extrascript %}
  <script>
    'use strict';
    var hide_btn = $("#hide_btn");
    hide_btn.click(function(){
        var disp = $("#disp");
        disp.fadeToggle();
    });
  </script>
{% endblock extrascript %}

templates/create-profile.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="main-content">
    <section class="section">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2">
            <div class="card card-warning">
              <div class="card-header">
              
              {% if request.user.profile.has_profile %}
                <h4>Update Profile</h4>
                {% else %}
                <h4>Create Profile</h4>

              {% endif %}
                
              </div>
              <div class="card-body">
              {% if request.user.profile.has_profile %}
              <form action="{% url 'golt:update-profile' profile.pk %}" method="post" enctype="multipart/form-data">

              {% else %}
              <form action="{% url 'golt:create-profile' %}" method="post" enctype="multipart/form-data">

              {% endif %}


                  {% csrf_token %}
                  <div class="row">
                    <div class="form-group col-6">
                      <label for="fcountry">Country</label>
                      <input id="fcountry" type="text" class="form-control" name="country" autofocus>
                    </div>
                  <div class="form-group col-6">
                    <label for="state">State</label>
                    <input id="state" type="text" class="form-control" name="state">
                    <div class="invalid-feedback">
                    </div>
                  </div>
                </div>
                  <div class="row">
                    <div class="form-group col-6">
                      <label for="zip" class="d-block">Zip</label>
                      <input id="zip" type="text" class="form-control pwstrength" data-indicator="pwindicator"
                        name="zip">
                      <div id="pwindicator" class="pwindicator">
                        <div class="bar"></div>
                        <div class="label"></div>
                      </div>
                    </div>
                    <div class="form-group col-6">
                      <label for="phone" class="d-block">Phone</label>
                      <input id="phone" type="phone" class="form-control" name="phone">
                    </div>
                  </div>
                  <div class="form-group row mb-4">
                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Profile Photo</label>
                    <div class="col-sm-12 col-md-7">
                        <div id="image-preview" class="image-preview">
                        <label for="image-upload" id="image-label">Choose File</label>
                        <input type="file" name="photo" id="image-upload" />
                        </div>
                    </div>
                    </div>
                  
                  <div class="form-group">
                    <div>
                      <!-- *this site uses user data to gather specific infos -->
                    </div>
                    <!-- <div class="custom-control custom-checkbox">
                      <input type="checkbox" name="agree" class="custom-control-input" id="agree">
                      <label class="custom-control-label" for="agree">I agree with the terms and conditions</label>
                    </div> -->
                  </div>
                  
                  <div class="form-group">
                  {% if request.user.profile.has_profile %}
                  <button type="submit" class="btn btn-warning btn-lg btn-block">
                    Update Profile
                  </button>
                  {% else %}

                    <button type="submit" class="btn btn-warning btn-lg btn-block">
                      Create Profile
                    </button>
                  {% endif %}

                  </div>
                </form>
              </div>
              <div class="mb-4 text-muted text-center">
                Already Registered? <a href="{% url 'account_login' %}">Login</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  
      <!-- Main Content -->
      <div class="main-content pt-5 mt-0">
        <section class="section">
          <div class="section-body pt-5">
            <div class="card">
              <div class="card-header">
                <h4>Just For You</h4>
              </div>
              <div class="card-body">
                <div id="carouselExampleIndicators2" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators2" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators2" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators2" data-slide-to="2"></li>
                  </ol>
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <img class="d-block w-100" src= {%  static "assets/img/blog/img05.png" %} alt="First slide">
                      <div class="carousel-caption d-none d-md-block">
                        <h5>Heading</h5>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                          tempor incididunt ut labore et dolore magna aliqua.</p>
                      </div>
                    </div>
                    <div class="carousel-item">
                      <img class="d-block w-100" src= {%  static "assets/img/blog/img10.png" %} alt="Second slide">
                      <div class="carousel-caption d-none d-md-block">
                        <h5>Heading</h5>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                          tempor incididunt ut labore et dolore magna aliqua.</p>
                      </div>
                    </div>
                    <div class="carousel-item">
                      <img class="d-block w-100" src= {%  static "assets/img/blog/img08.png" %} alt="Third slide">
                      <div class="carousel-caption d-none d-md-block">
                        <h5>Heading</h5>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                          tempor incididunt ut labore et dolore magna aliqua.</p>
                      </div>
                    </div>
                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleIndicators2" role="button"
                    data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleIndicators2" role="button"
                    data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
              </div>
            </div>
            <h2 class="section-title h4">Trending Ads</h2>
            <div class="row">
                {% for ad in query  %}
                  
              <div class="col-12 col-md-4 col-lg-4">
                <article class="article article-style-c">
                  <div class="article-header">
                    <div class="article-image" data-background={{ad.photo.url}}>
                    </div>
                    <div class="article-badge">
                      <div class="article-badge-item bg-danger"><i class="fas fa-fire"></i> Trending</div>
                    </div>
                    <div class="article-badge ml-5">
                        <div class="article-badge-item bg-warning ml-5"><i class="
                            fas fa-audio-description"></i>{{ad.package_type}} Ads</div>
                      </div>
                  </div>
                  <div class="article-details">
                    <div class="article-category"><a href="#">{{ad.ad_type}}</a>
                      <div class="bullet"></div> <a href="#">date</a>
                    </div>
                    <div class="article-title">
                      <h2><a href="{% url 'golt:adcheck' user.pk ad.pk %}" id="site">Visit Site</a></h2>
                    </div>
                    <p id="ad-v">{{ad.ad_name}}</p>
                    <div class="article-user">
                      <img alt="company-logo" src= {%  static "assets/img/users/user-1.png" %} >
                      <div class="article-user-details">
                        <div class="user-detail-name">
                          <a href="{% url 'golt:company' ad.company.pk %}">{{ad.company.company_name}}</a>
                        </div>
                        <div class="text-job">Location</div>
                      </div>
                    </div>
                  </div>
                </article>
              </div>
              {% endfor %}

              </div>
            </div>
          </div>
        </section>
        
      </div>
      
{% endblock content %}
{% block extrascript %}
  <script>
    
    var site = $("#site");
    site.click(function(){
      window.open(" {{ad.ad_link}} ");
    });
    
  </script>
{% endblock extrascript %}

templates/initiate_payment.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="main-content">
    <section class="section">
      <div class="section-body">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Make Payment</h4>
              </div>
              <div class="card-body">
                  <form action="{% url 'mgt:initiate-payment' %}" method="post">
                      {% csrf_token %}
                      <div class="form-group">
                        <label>amount*</label>
                        <input type="text" class="form-control creditcard" name="amount">
                      </div>
                      <div class="form-group">
                        <label>email*</label>
                        <input type="email" class="form-control email" name="email">
                      </div>
                      <div class="form-group">
                        <label>account number*</label>
                        <input type="text" class="form-control creditcard" name="account">
                      </div>
                      <div class="form-group">
                        <label>bank code*</label>
                        <input type="text" class="form-control email" name="bank_code">
                      </div>
                       <div class="form-group">
                        <label>card details*</label>
                        <input type="text" class="form-control " name="card_details">
                      </div>
                      
                      <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                      <div class="col-sm-12 col-md-7">
                          <button class="btn btn-primary" type="submit">Make Payment</button>
                      </div>
                      </div>
                  </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock content %}